#!/usr/bin/env python
"""Prove the migration chain against a real database. Destructive — scratch DBs only.

What a passing run demonstrates:

  1. `alembic upgrade head` produces exactly the model schema (`alembic check`
     finds no drift). This is the property the old create_all() bootstrap could
     never test, because it never ran the migrations.
  2. `alembic downgrade base` leaves a genuinely empty database — no tables, no
     enum types, no trigger function — and `upgrade head` rebuilds it. That is
     the rollback a change-controlled environment asks for.
  3. The legacy bridge in scripts/bootstrap_db.py works: a database stamped at a
     pre-squash revision is carried through app/alembic/versions_legacy/ to the
     live root and on to head, and the result still matches the models.

CI runs this after the integration tests, against the same scratch database
(the data they left behind is dropped with the tables, which is the point of
testing downgrade on a populated schema). Locally:

    ./run-tests-live.sh --migrations

Exit status is non-zero on the first failed step.
"""
from __future__ import annotations

import subprocess
import sys

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from app.core.config import db_url_for, settings

LIVE_ROOT = "e0f1a2b3c4d5"          # squashed initial schema == legacy head
LEGACY_ONE_BEFORE_HEAD = "d9e0f1a2b3c4"
LEGACY_VERSIONS = "app/alembic/versions_legacy"


def log(msg: str) -> None:
    print(f"[verify-migrations] {msg}", flush=True)


def cfg(*, legacy: bool = False) -> Config:
    c = Config("alembic.ini")
    if legacy:
        c.set_main_option("version_locations", LEGACY_VERSIONS)
    return c


def db_state() -> dict:
    engine = create_engine(db_url_for(settings.DATABASE_URL, sync=True))
    try:
        with engine.connect() as conn:
            tables = set(inspect(conn).get_table_names())
            enums = {r[0] for r in conn.execute(text(
                "SELECT t.typname FROM pg_type t JOIN pg_namespace n "
                "ON n.oid = t.typnamespace WHERE n.nspname = 'public' "
                "AND t.typtype = 'e'"))}
            functions = {r[0] for r in conn.execute(text(
                "SELECT proname FROM pg_proc WHERE proname LIKE 'traceiq_%'"))}
            triggers = {r[0] for r in conn.execute(text(
                "SELECT tgname FROM pg_trigger WHERE tgname LIKE 'traceiq_%'"))}
            try:
                stamps = [r[0] for r in conn.execute(
                    text("SELECT version_num FROM alembic_version"))]
            except Exception:
                stamps = []
                conn.rollback()
    finally:
        engine.dispose()
    return {"tables": tables, "enums": enums, "functions": functions,
            "triggers": triggers, "stamps": stamps}


def expect(condition: bool, message: str) -> None:
    if not condition:
        log(f"FAIL: {message}")
        sys.exit(1)
    log(f"ok: {message}")


def check_no_drift(label: str) -> None:
    try:
        command.check(cfg())
    except AutogenerateDiffsDetected as exc:
        log(f"FAIL: {label}: migrations and models differ:\n{exc}")
        sys.exit(1)
    log(f"ok: {label}: schema matches the models")


def head_revision() -> str:
    from alembic.script import ScriptDirectory
    heads = ScriptDirectory.from_config(cfg()).get_heads()
    expect(len(heads) == 1, f"live chain has exactly one head ({heads})")
    return heads[0]


def main() -> int:
    head = head_revision()

    # --- 1. wherever we start, head must equal the models ------------------
    log("step 1: upgrade head, then compare with the models")
    command.upgrade(cfg(), "head")
    st = db_state()
    expect(st["stamps"] == [head], f"stamped at head {head}")
    expect({"traceiq_auditlog_no_update", "traceiq_auditlog_no_delete"}
           <= st["triggers"], "append-only audit triggers present")
    check_no_drift("after upgrade head")

    # --- 2. full rollback and rebuild --------------------------------------
    log("step 2: downgrade base must leave an empty database")
    command.downgrade(cfg(), "base")
    st = db_state()
    expect(st["tables"] <= {"alembic_version"},
           f"no application tables remain (left: {sorted(st['tables'] - {'alembic_version'})})")
    expect(not st["enums"], f"no enum types remain (left: {sorted(st['enums'])})")
    expect(not st["functions"], f"no trigger functions remain (left: {sorted(st['functions'])})")
    command.upgrade(cfg(), "head")
    check_no_drift("after downgrade base + upgrade head")

    # --- 3. the legacy bridge ----------------------------------------------
    log("step 3: a database stamped inside the legacy chain must reach head")
    # Put the database one legacy step behind the root: stamp the root (the
    # only revision both chains share), then let the LEGACY chain downgrade
    # one step, which really removes the F4 columns.
    command.stamp(cfg(), LIVE_ROOT)
    command.downgrade(cfg(legacy=True), LEGACY_ONE_BEFORE_HEAD)
    st = db_state()
    expect(st["stamps"] == [LEGACY_ONE_BEFORE_HEAD],
           f"stamped at legacy revision {LEGACY_ONE_BEFORE_HEAD}")
    engine = create_engine(db_url_for(settings.DATABASE_URL, sync=True))
    with engine.connect() as conn:
        cols = {c["name"] for c in inspect(conn).get_columns("caseproposal")}
    engine.dispose()
    expect("created_by_id" not in cols, "legacy downgrade really changed the schema")

    # bootstrap_db.py is what the container runs; exercise it as a process so
    # the advisory lock and the chain detection are covered too.
    proc = subprocess.run([sys.executable, "scripts/bootstrap_db.py"],
                          capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    expect(proc.returncode == 0, "bootstrap_db.py exits 0 from a legacy revision")
    expect("LEGACY revision" in proc.stdout, "bootstrap_db.py took the legacy bridge")
    st = db_state()
    expect(st["stamps"] == [head], f"bridged database is at head {head}")
    check_no_drift("after the legacy bridge")

    log("all migration checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
