#!/usr/bin/env bash
# First-boot initialisation for the TraceIQ all-in-one image, then hands off
# to supervisord.
#
# Secrets are generated HERE, on the user's machine, into the /data volume —
# never baked into the image. Every AIO deployment therefore has unique
# credentials, same invariant as the compose distribution.
set -euo pipefail

# stderr, so log lines can never leak into files built from redirected stdout
# (the first-boot secrets loop below writes its stdout to secrets.env).
log() { echo "[traceiq-aio] $*" >&2; }

DATA=/data
RUN_DIR=/run/traceiq
PG_BIN=/usr/lib/postgresql/15/bin

mkdir -p "${RUN_DIR}" "${RUN_DIR}/beat" /var/run/postgresql /tmp/artifacts
mkdir -p "${DATA}/postgres" "${DATA}/redis" "${DATA}/minio"

# --- Secrets (first boot only; persisted in the volume) ---------------------
# Auto-generated by default, but any of these passed with `docker run -e`
# on the FIRST boot is used instead, so operators can bring their own values.
SECRET_VARS="SECRET_KEY WEBHOOK_SECRET POSTGRES_PASSWORD REDIS_PASSWORD MINIO_ROOT_USER MINIO_ROOT_PASSWORD"

if [ ! -f "${DATA}/secrets.env" ]; then
  # Validate supplied signing secrets now, with a readable message, rather
  # than letting the backend crash-loop on them later.
  for v in SECRET_KEY WEBHOOK_SECRET; do
    val="${!v:-}"
    if [ -n "${val}" ] && [ "${#val}" -lt 32 ]; then
      log "ERROR: supplied ${v} is only ${#val} characters; the backend refuses"
      log "       anything under 32. Generate one with: openssl rand -hex 32"
      exit 1
    fi
  done
  if [ -n "${SECRET_KEY:-}" ] && [ "${SECRET_KEY:-}" = "${WEBHOOK_SECRET:-}" ]; then
    log "ERROR: SECRET_KEY and WEBHOOK_SECRET must differ so they can be rotated independently."
    exit 1
  fi
  if [ "${MINIO_ROOT_USER:-}" = "minioadmin" ]; then
    log "ERROR: MINIO_ROOT_USER must not be minioadmin (the well-known default)."
    exit 1
  fi
  # These get embedded in connection URLs, SQL, and redis.conf; one charset
  # rule avoids three different escaping bugs.
  for v in POSTGRES_PASSWORD REDIS_PASSWORD; do
    val="${!v:-}"
    if [ -n "${val}" ] && ! printf '%s' "${val}" | grep -qE '^[A-Za-z0-9._~-]+$'; then
      log "ERROR: supplied ${v} may only contain letters, digits, and . _ ~ -"
      log "       (it is embedded in connection URLs). Try: openssl rand -hex 24"
      exit 1
    fi
  done
  # MinIO creds are written into per-service env files and expanded by the
  # shell; a literal '$', whitespace, or newline would corrupt the value (or
  # splice extra lines). Reject those (looser than the URL charset above, since
  # these are not embedded in DSNs).
  for v in MINIO_ROOT_USER MINIO_ROOT_PASSWORD; do
    val="${!v:-}"
    if [ -n "${val}" ] && { [[ "${val}" =~ [[:space:]] ]] || [[ "${val}" == *'$'* ]]; }; then
      log "ERROR: supplied ${v} must not contain '\$', whitespace, or newlines."
      exit 1
    fi
  done

  log "First boot: writing instance secrets -> /data/secrets.env"
  umask 077
  for v in ${SECRET_VARS}; do
    val="${!v:-}"
    if [ -n "${val}" ]; then
      log "  ${v}: supplied via -e"
    else
      case "${v}" in
        SECRET_KEY|WEBHOOK_SECRET) val="$(openssl rand -hex 32)" ;;
        MINIO_ROOT_USER) val="traceiq-$(openssl rand -hex 4)" ;;
        *) val="$(openssl rand -hex 24)" ;;
      esac
      log "  ${v}: auto-generated"
    fi
    printf '%s=%s\n' "${v}" "${val}"
  done > "${DATA}/secrets.env"
  umask 022
else
  # Stored values always win after first boot: rotating e.g. the postgres
  # password needs more than an env change (the database itself must agree),
  # so a differing -e value would otherwise be silently ignored. Say so.
  for v in ${SECRET_VARS}; do
    envval="${!v:-}"
    [ -n "${envval}" ] || continue
    stored="$(grep -E "^${v}=" "${DATA}/secrets.env" | head -1 | cut -d= -f2-)"
    if [ "${envval}" != "${stored}" ]; then
      log "WARNING: -e ${v} differs from the value stored in /data/secrets.env."
      log "         The stored value stays in effect. To start over with new"
      log "         secrets, remove the volume (this destroys all data)."
    fi
  done
fi

# Load literally (no shell quote removal — values may contain any character).
while IFS= read -r line; do
  case "${line}" in ''|'#'*) continue ;; esac
  export "${line?}"
done < "${DATA}/secrets.env"

# --- User-overridable settings (docker run -e VAR=... wins) -----------------
: "${FRONTEND_BASE_URL:=http://localhost:8080}"
: "${MINIO_PUBLIC_URL:=http://localhost:9000}"
: "${BACKEND_CORS_ORIGINS:=[\"http://localhost:8080\"]}"
: "${ALLOW_PRIVATE_NETWORK_TARGETS:=false}"
: "${OUTBOUND_ALLOWED_HOSTS:=[]}"
: "${RUN_RETENTION_DAYS:=90}"
: "${RAW_PLAYWRIGHT_ENABLED:=false}"
: "${RUNTIME_HEAL_ENABLED:=false}"
: "${DEFAULT_TIMEOUT:=30000}"
: "${CELERY_CONCURRENCY:=2}"
: "${LLM_PROVIDER:=}"; : "${LLM_MODEL:=}"
: "${ANTHROPIC_API_KEY:=}"; : "${OPENAI_API_KEY:=}"; : "${GEMINI_API_KEY:=}"
: "${OLLAMA_BASE_URL:=}"; : "${LLM_BASE_URL:=}"; : "${LLM_API_KEY:=}"
: "${NOTIFICATIONS_ENABLED:=false}"; : "${EMAIL_NOTIFICATIONS_ENABLED:=false}"
: "${SMTP_HOST:=}"; : "${SMTP_PORT:=587}"; : "${SMTP_USER:=}"
: "${SMTP_PASSWORD:=}"; : "${SMTP_FROM:=noreply@example.com}"
: "${SLACK_WEBHOOK_URL:=}"; : "${TEAMS_WEBHOOK_URL:=}"
# supervisord.conf interpolates this one (%(ENV_CELERY_CONCURRENCY)s), so it
# must be in supervisord's environment, not just this shell.
export CELERY_CONCURRENCY

# --- Render per-service env files -------------------------------------------
# Passwords are embedded in connection URLs, and user-supplied ones (unlike
# generated hex) can contain URL-reserved characters — encode them.
urlenc() { python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1"; }
PG_PASS_ENC="$(urlenc "${POSTGRES_PASSWORD}")"
REDIS_PASS_ENC="$(urlenc "${REDIS_PASSWORD}")"

# Two files because MINIO_ENDPOINT means host:port to the backend but
# host-only (plus MINIO_PORT) to the node worker.
umask 027
cat > "${RUN_DIR}/backend.env" <<EOF
ENVIRONMENT=production
DATABASE_URL=postgresql+asyncpg://traceiq:${PG_PASS_ENC}@127.0.0.1:5432/traceiq
CELERY_BROKER_URL=redis://:${REDIS_PASS_ENC}@127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://:${REDIS_PASS_ENC}@127.0.0.1:6379/0
MINIO_ENDPOINT=127.0.0.1:9000
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
SECRET_KEY=${SECRET_KEY}
WEBHOOK_SECRET=${WEBHOOK_SECRET}
BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
ALLOW_PRIVATE_NETWORK_TARGETS=${ALLOW_PRIVATE_NETWORK_TARGETS}
OUTBOUND_ALLOWED_HOSTS=${OUTBOUND_ALLOWED_HOSTS}
RUN_RETENTION_DAYS=${RUN_RETENTION_DAYS}
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
GEMINI_API_KEY=${GEMINI_API_KEY}
OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
LLM_BASE_URL=${LLM_BASE_URL}
LLM_API_KEY=${LLM_API_KEY}
NOTIFICATIONS_ENABLED=${NOTIFICATIONS_ENABLED}
EMAIL_NOTIFICATIONS_ENABLED=${EMAIL_NOTIFICATIONS_ENABLED}
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_FROM=${SMTP_FROM}
SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
TEAMS_WEBHOOK_URL=${TEAMS_WEBHOOK_URL}
EOF

cat > "${RUN_DIR}/worker.env" <<EOF
REDIS_URL=redis://:${REDIS_PASS_ENC}@127.0.0.1:6379/0
REDIS_JOBS_STREAM=jobs:pending
REDIS_RESULTS_STREAM=jobs:results
REDIS_CONSUMER_GROUP=execution-workers
MINIO_ENDPOINT=127.0.0.1
MINIO_PORT=9000
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET_NAME=test-artifacts
BACKEND_URL=http://127.0.0.1:8000
WEBHOOK_SECRET=${WEBHOOK_SECRET}
DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}
ARTIFACTS_DIR=/tmp/artifacts
WORKER_IDLE_TIMEOUT=0
MAX_JOBS_BEFORE_RESTART=50
RAW_PLAYWRIGHT_ENABLED=${RAW_PLAYWRIGHT_ENABLED}
RUNTIME_HEAL_ENABLED=${RUNTIME_HEAL_ENABLED}
LLM_PROVIDER=${LLM_PROVIDER}
LLM_MODEL=${LLM_MODEL}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
EOF
umask 022
chown root:traceiq "${RUN_DIR}/backend.env" "${RUN_DIR}/worker.env"
chown traceiq:traceiq "${RUN_DIR}/beat" /tmp/artifacts

# --- Redis config -----------------------------------------------------------
cat > "${RUN_DIR}/redis.conf" <<EOF
bind 127.0.0.1
port 6379
dir /data/redis
appendonly yes
requirepass ${REDIS_PASSWORD}
EOF
chown redis:redis "${RUN_DIR}/redis.conf" "${DATA}/redis"
chmod 600 "${RUN_DIR}/redis.conf"

# --- MinIO data -------------------------------------------------------------
chown -R traceiq:traceiq "${DATA}/minio"

# --- Postgres init ----------------------------------------------------------
chown postgres:postgres /var/run/postgresql
chown -R postgres:postgres "${DATA}/postgres"
chmod 700 "${DATA}/postgres"

if [ ! -s "${DATA}/postgres/PG_VERSION" ]; then
  log "First boot: initialising PostgreSQL in /data/postgres"
  runuser -u postgres -- "${PG_BIN}/initdb" -D "${DATA}/postgres" \
    --auth-local=peer --auth-host=scram-sha-256 --encoding=UTF8 >/dev/null
fi

# Role/database setup is idempotent and re-syncs the password each boot, so a
# regenerated secrets.env (user deleted it) cannot strand the app.
log "Starting PostgreSQL for setup..."
runuser -u postgres -- "${PG_BIN}/pg_ctl" -D "${DATA}/postgres" \
  -o "-c listen_addresses=127.0.0.1" -w -t 60 start >/dev/null

if ! runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='traceiq'" | grep -q 1; then
  runuser -u postgres -- psql -qc "CREATE ROLE traceiq LOGIN"
fi
runuser -u postgres -- psql -qc "ALTER ROLE traceiq PASSWORD '${POSTGRES_PASSWORD}'"
if ! runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_database WHERE datname='traceiq'" | grep -q 1; then
  runuser -u postgres -- createdb -O traceiq traceiq
fi
runuser -u postgres -- "${PG_BIN}/pg_ctl" -D "${DATA}/postgres" -m fast -w stop >/dev/null

cat <<EOF
============================================================================
 TraceIQ all-in-one starting.

   UI:        ${FRONTEND_BASE_URL}  (after startup finishes — first boot
              runs database migrations and takes a minute or two)
   Artifacts: ${MINIO_PUBLIC_URL}   (must be reachable by your BROWSER;
              override with -e MINIO_PUBLIC_URL=... when serving remotely)

   The FIRST account registered becomes the workspace admin.

   Secrets for this instance live in the volume at /data/secrets.env.
   Testing apps on private/LAN addresses? Re-run with
   -e ALLOW_PRIVATE_NETWORK_TARGETS=true (read the docs first).

   This image is the evaluation tier — for production self-hosting use
   docker-compose.community.yml (see SELF_HOSTING.md).
============================================================================
EOF

exec supervisord -c /etc/traceiq/supervisord.conf
